Pagination, Sorting, and Swagger
VictoriaKh-T/book-strore pull request #13
Opened 2023-08-22 13:40 UTC by VictoriaKh-T

2023-08-22 16:49 UTC, aaananas requested changes

2023-08-22 16:49 UTC, aaananas commented on src/main/java/mate/academy/bookstore/controller/BookController.java
>      @GetMapping
lets add a description in swagger to each endpoint

2023-08-23 09:10 UTC, Rommelua requested changes

2023-08-23 09:10 UTC, Rommelua commented on src/main/java/mate/academy/bookstore/controller/BookController.java
>      public List<BookDto> searchBooks(BookSearchParametersDto searchParameters) {
lets add Pageable here as well

2023-08-23 17:35 UTC, aaananas approved these changes

2023-08-29 13:20 UTC, merged